###############################
# ------ DO NOT MODIFY ------ #
###############################
PATH_ROOT = ""
VERSION = "0.0.1"
VERSION_SY_CFG = "0.0.1"

VERSION_UI_GUI = "0.0.1"
VERSION_UI_WEB = "0.0.0"

VERSION_CMP_SYNOPSIS = "0.0.1"
VERSION_CMP_VENTURE = "0.0.1"
VERSION_CMP_PROJECT = "0.0.1"

VERSION_CFG_SYNOPSIS = "0.0.1"
VERSION_CFG_VENTURE = "0.0.1"
VERSION_CFG_PROJECT = "0.0.1"

VERSION_MGR_SYNOPSIS = "0.0.1"
VERSION_MGR_VENTURE = "0.0.1"
VERSION_MGR_PROJECT = "0.0.1"